// dummyMatches.ts
import { Match } from "./TournamentBracket";

export const teamDatabase = [
  { team_id: 101, name: "Team Alpha", university: "Cornell" },
  { team_id: 102, name: "Team Beta", university: "RIT" },
  { team_id: 103, name: "Team Gamma", university: "Penn State" },
  { team_id: 104, name: "Team Delta", university: "Binghamton" },
  { team_id: 105, name: "Team Epsilon", university: "NYU" },
  { team_id: 106, name: "Team Zeta", university: "UCLA" },
  { team_id: 107, name: "Team Theta", university: "MIT" },
  { team_id: 108, name: "Team Iota", university: "Harvard" },
  { team_id: 109, name: "Team Kappa", university: "Duke" },
  { team_id: 110, name: "Team Lambda", university: "Stanford" },
  { team_id: 111, name: "Team Mu", university: "Berkeley" },
  { team_id: 112, name: "Team Nu", university: "Yale" },
  { team_id: 113, name: "Team Xi", university: "Columbia" },
  { team_id: 114, name: "Team Omicron", university: "Princeton" },
  { team_id: 115, name: "Team Pi", university: "Georgetown" },
  { team_id: 116, name: "Team Rho", university: "UChicago" },
  { team_id: 117, name: "Team Sigma", university: "Johns Hopkins" },
  { team_id: 118, name: "Team Tau", university: "Brown" },
  { team_id: 119, name: "Team Upsilon", university: "USC" },
  { team_id: 120, name: "Team Phi", university: "Northwestern" },
  { team_id: 121, name: "Team Chi", university: "Notre Dame" },
  { team_id: 122, name: "Team Psi", university: "Dartmouth" },
  { team_id: 123, name: "Team Omega", university: "Texas A&M" },
  { team_id: 124, name: "Team Alpha2", university: "UNC" },
  { team_id: 125, name: "Team Beta2", university: "Michigan" },
  { team_id: 126, name: "Team Gamma2", university: "Ohio State" },
  { team_id: 127, name: "Team Delta2", university: "Wisconsin" },
  { team_id: 128, name: "Team Epsilon2", university: "Washington" },
  { team_id: 129, name: "Team Zeta2", university: "Florida" },
  { team_id: 130, name: "Team Eta2", university: "Virginia" },
  { team_id: 131, name: "Team Theta2", university: "Illinois" },
  { team_id: 132, name: "Team Iota2", university: "Georgia Tech" },
];

const dummyMatches: Match[] = [
  // Round 1
  {
    match_id: 1,
    tournament_id: 1,
    team1_id: 101,
    team2_id: 102,
    score_team1: 0,
    score_team2: 3,
    winner_id: 102,
    start_time: "2025-03-24",
    status: 1,
    team1_name: "Team Alpha",
    team2_name: "Team Beta",
    team1_university: "Cornell",
    team2_university: "RIT",
  },
  {
    match_id: 2,
    tournament_id: 1,
    team1_id: 103,
    team2_id: 104,
    score_team1: 4,
    score_team2: 2,
    winner_id: 103,
    start_time: "2025-03-24",
    status: 1,
    team1_name: "Team Gamma",
    team2_name: "Team Delta",
    team1_university: "Penn State",
    team2_university: "Binghamton",
  },
  {
    match_id: 3,
    tournament_id: 1,
    team1_id: 105,
    team2_id: 106,
    score_team1: 1,
    score_team2: 5,
    winner_id: 106,
    start_time: "2025-03-24",
    status: 1,
    team1_name: "Team Epsilon",
    team2_name: "Team Zeta",
    team1_university: "NYU",
    team2_university: "UCLA",
  },
  {
    match_id: 4,
    tournament_id: 1,
    team1_id: 107,
    team2_id: 108,
    score_team1: 2,
    score_team2: 4,
    winner_id: 108,
    start_time: "2025-03-24",
    status: 1,
    team1_name: "Team Theta",
    team2_name: "Team Iota",
    team1_university: "MIT",
    team2_university: "Harvard",
  },
  {
    match_id: 5,
    tournament_id: 1,
    team1_id: 109,
    team2_id: 110,
    score_team1: 6,
    score_team2: 3,
    winner_id: 109,
    start_time: "2025-03-24",
    status: 1,
    team1_name: "Team Kappa",
    team2_name: "Team Lambda",
    team1_university: "Duke",
    team2_university: "Stanford",
  },
  {
    match_id: 6,
    tournament_id: 1,
    team1_id: 111,
    team2_id: 112,
    score_team1: 2,
    score_team2: 1,
    winner_id: 111,
    start_time: "2025-03-24",
    status: 1,
    team1_name: "Team Mu",
    team2_name: "Team Nu",
    team1_university: "Berkeley",
    team2_university: "Yale",
  },
  {
    match_id: 7,
    tournament_id: 1,
    team1_id: 113,
    team2_id: 114,
    score_team1: 5,
    score_team2: 7,
    winner_id: 114,
    start_time: "2025-03-24",
    status: 1,
    team1_name: "Team Xi",
    team2_name: "Team Omicron",
    team1_university: "Columbia",
    team2_university: "Princeton",
  },
  {
    match_id: 8,
    tournament_id: 1,
    team1_id: 115,
    team2_id: 116,
    score_team1: 0,
    score_team2: 2,
    winner_id: 116,
    start_time: "2025-03-24",
    status: 1,
    team1_name: "Team Pi",
    team2_name: "Team Rho",
    team1_university: "Georgetown",
    team2_university: "UChicago",
  },

  // Round 2 to Round 5 (Unplayed matches with default values)
  ...Array.from({ length: 23 }, (_, i) => {
    const id = i + 9;
    return {
      match_id: id,
      tournament_id: 1,
      team1_id: 200 + id * 2,
      team2_id: 201 + id * 2,
      score_team1: null,
      score_team2: null,
      winner_id: null,
      start_time: null,
      status: 0,
      team1_name: "Team Name",
      team2_name: "Team Name",
      team1_university: "School",
      team2_university: "School",
    };
  }),
];

export default dummyMatches;
